version: '3'

# START
# docker-compose up -d
#
# SHUTDOWN
# docker-compose down

services:
  mongodb:
    image: mongo:3.6-stretch
    ports:
      - '27017:27017'
    volumes:
      - mongo-data-db:/data/db
      - mongo-data-configdb:/data/configdb

volumes:
  mongo-data-db:
  mongo-data-configdb:
